/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.broadinstitute.pgen;

import org.testng.annotations.*;
import static org.testng.Assert.*;

public class PgenWriteTest {
    @Test public void someLibraryMethodReturnsTrue() {
        PgenWrite classUnderTest = new PgenWrite();
        assertTrue(classUnderTest.test(), "someLibraryMethod should return 'true'");
    }
}
