/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.broadinstitute.pgen;

public class PgenWrite {

    static {
        System.loadLibrary("pgen");
    }

    public boolean test(){
        return init();
    }

    private static native boolean init();
}
