/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.broadinstitute.pgen;

import htsjdk.io.HtsPath;
import htsjdk.variant.variantcontext.VariantContext;
import htsjdk.variant.variantcontext.writer.VariantContextWriter;
import htsjdk.variant.vcf.VCFHeader;


public class PgenWriter implements VariantContextWriter {

    private final long bookKeepingHandle;

    static {
        System.loadLibrary("pgen");
    }

    public PgenWriter(HtsPath file, long numberOfVariants, int numberOfSamples){
        bookKeepingHandle = createPgenMetadata();
        if(openPgen(file.getRawInputString(), numberOfVariants, numberOfSamples, bookKeepingHandle ) != 0){
            throw new RuntimeException("failed");
        }
    }

    @Override
    public void writeHeader(final VCFHeader header) {

    }


    @Override
    public void close() {

    }

    @Override
    public boolean checkError() {
        return false;
    }

    @Override
    public void add(final VariantContext vc) {

    }

    @Override
    public void setHeader(final VCFHeader header) {

    }

    private static native long createPgenMetadata();
    private static native int openPgen(String file, long numberOfVariants, long numberOfSamples, long bookKeepingHandle);
}
